name: resmat
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1
flutter_redux: ^0.5.3 
redux: ^3.0.0
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  translator: ^0.1.2
  path_provider: ^1.6.7
  flutter:
    sdk: flutter
  shared_preferences: ^0.4.2

#Para alteração de idioma
  flutter_localizations:
    sdk: flutter

  intl: ^0.16.1

cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - images/
    - lang/en.json
    - lang/pt.json

