name: resmat
description: A new Flutter project.


environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  translator: ^0.1.2
  path_provider: ^1.6.7
  flutter:
    sdk: flutter
    
  shared_preferences: ^0.4.2

#Para alteração de idioma
  flutter_localizations:
    sdk: flutter

  intl: ^0.16.1

cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  fonts:
    - family: Myriad
      fonts:
        - asset: fonts/myriad-italic.ttf
          style: italic
    - family: Myriad-Bold
      fonts:
        - asset: fonts/MyriadPro.ttf
          weight: 800

    - family: Myriad-Italic-Bold
      fonts:
        - asset: fonts/myriad-apple-bold-italic.ttf
          weight: 800

    - family: Myriad-Regular
      fonts:         
        - asset: fonts/myriadregular.ttf
      
          weight: 700
  uses-material-design: true

  assets:
    - images/
    - lang/en.json
    - lang/pt.json

  
